# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('model', models.CharField(max_length=32)),
                ('hardware', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, null=True)),
                ('memory', models.CharField(max_length=32, null=True)),
                ('cpu_model', models.CharField(max_length=32, null=True)),
                ('vender', models.CharField(max_length=32, null=True)),
                ('product', models.CharField(max_length=32, null=True)),
                ('sn', models.CharField(max_length=64, null=True)),
                ('osver', models.CharField(max_length=32, null=True)),
                ('cpu_num', models.CharField(max_length=10, null=True)),
                ('ip', models.CharField(max_length=32)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='BussinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role')),
            ],
            options={
                'verbose_name_plural': '业务线表',
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='Email')),
                ('auth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='用户权限')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='bussiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BussinessLine'),
        ),
        migrations.AddField(
            model_name='asset',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Env'),
        ),
    ]
